### ISSUE TITLE
Extension not working

### ISSUE THREAD

**Issue by itbankas** [Pasupathi-Rajamanickam/chrome-response-override#7]
At first, thank you for a good idea and your knowledge !!!

I am trying a few of your samples but without success

Example1:
url: https://nuomaklaipeda.com/
contains: /
Find: Trumpalaike nuoma
Replace: Ilgalaike nuoma
Save => Play => Refresh => Nothing

Example1:
url: https://api.recurly.com/js/v1/coupons/any
contains: /any
Find: error
Replace: terror
Save => Play => Refresh => Nothing

**Comment by Pasupathi-Rajamanickam** [comment]
Thank you for reporting. Appreciate your contribution. :smile: 

I definitely broke URL contains "/"
but other one working fine.

Since "/" broken other might not work for you. I would suggest to click "Stop" or Cancel button on chrome/opera info bar saying "Chrome Response Override" is debugging this tab, if running.

And remove URL rule with "/"  Just have URL contains "any" and or other rules you should be able to see response got overridden.

Will get a fix for "/" like just domain name page override and publish.

![image](https://user-images.githubusercontent.com/12167873/102022628-b39b2f00-3d4d-11eb-9ba1-f5fe3f8d2f48.png)

**Comment by Pasupathi-Rajamanickam** [comment]
Fixed issue, Published plugin, will take few days to update. Will update this thread once ready for usage.

**Comment by itbankas** [comment]
Thanks a lot !
Yesterday I tried on another PC and it's working
Really great tool :)

<https://nobeds.com/>

NOBEDS.COM <http://nobeds.com/> - Free hotel management system

*Support team* - Saulius Chomentauskas

Mazoji smilties str. 2, Klaipėda

LT-91247, Lithuania, +370 611 54 444

support@nobeds.com


<https://www.youtube.com/channel/UCMa4zsrXPUDjiS688dP5dYw?sub_confirmation=1>



This e-mail may contain confidential and/or privileged information. If you
are not the intended recipient please notify the sender immediately and
destroy this e-mail. Any unauthorized copying, disclosure or distribution
of the material in this e-mail is strictly forbidden.
